export const GOOGLE_AUTH_REQUEST = 'GOOGLE_AUTH_REQUEST';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAILURE = 'GOOGLE_AUTH_FAILURE';

export const FB_AUTH_REQUEST = 'FB_AUTH_REQUEST';
export const FB_AUTH_SUCCESS = 'FB_AUTH_SUCCESS';
export const FB_AUTH_FAILURE = 'FB_AUTH_FAILURE';

export const KAKAO_AUTH_REQUEST = 'KAKAO_AUTH_REQUEST';
export const KAKAO_AUTH_SUCCESS = 'KAKAO_AUTH_SUCCESS';
export const KAKAO_AUTH_FAILURE = 'KAKAO_AUTH_FAILURE';

export const SIGN_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'LOG_OUT_FAILURE';
